### PR TITLE
This would be much easier if you gave me access!

### PR DESCRIPTION
**Pull request by zacharyacutey**
Please, I'll only fix your ERRORS!!!!!
(I won't try to change anything that works)

### CODE REVIEW

**Comment by JoinRajuncraftNow** [comment]
I have to add externs for alot of stuff.

**Comment by zacharyacutey** [comment]
D is SO MUCH WORSE HERE:
You have to find where it is declared and selectively import it from there.
(But it's so much easier to START it in D)

**Comment by JoinRajuncraftNow** [comment]
kkk

**Comment by zacharyacutey** [comment]
JUST GIVE ME ACCESS!!!!

**Pull request merged**
